{
 "title": "EMQX Auth Details",
 "description": "EMQX Authentication and Authorization Details",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "NodeName",
    "query": {
     "query": "label_values(emqx_authn_enable,node)"
    }
   },
   {
    "name": "id",
    "label": "ID",
    "query": {
     "query": "label_values(emqx_authn_enable,id)"
    }
   },
   {
    "name": "type",
    "label": "Type",
    "query": {
     "query": "label_values(emqx_authz_enable,type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "AuthN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Switch Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(emqx_authn_enable{id='$id'}) / count(emqx_authn_enable{id='$id'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(emqx_authn_status{id='$id'}) / count(emqx_authn_status{id='$id'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users Count: password_based",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(emqx_authn_users_count{id=\"password_based:built_in_database\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users Count: scram",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(emqx_authn_users_count{id=\"scram:built_in_database\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentication Rate",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 14, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(emqx_authn_total{job=\"emqx-auth\",node='$node'}[$__interval]) or irate(emqx_authn_total{job=\"emqx-auth\",node='$node'}[$__interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(emqx_authn_success{job=\"emqx-auth\",node='$node'}[$__interval]) or irate(emqx_authz_success{job=\"emqx-auth\",node='$node'}[$__interval]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(rate(emqx_authn_failed{job=\"emqx-auth\",node='$node'}[$__interval]) or irate(emqx_authn_failed{job=\"emqx-auth\",node='$node'}[$__interval]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(rate(emqx_authn_nomatch{job=\"emqx-auth\",node='$node'}[$__interval]) or irate(emqx_authn_nomatch{job=\"emqx-auth\",node='$node'}[$__interval]))",
     "legendFormat": "No Match"
    }
   ]
  },
  {
   "title": "Match Total",
   "type": "stat",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(emqx_authn_total{id='$id'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(emqx_authn_success{id='$id'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deny Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(emqx_authn_failed{id='$id'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No Match Counh",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(emqx_authn_nomatch{id='$id'})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "AuthZ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Switch Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(emqx_authz_enable{type='$type'}) / count(emqx_authz_enable{type='$type'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(emqx_authz_status{type='$type'}) / count(emqx_authz_status{type='$type'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rules Count: built_in_database",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(emqx_authz_rules_count{type=\"built_in_database\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rules Count: file",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(emqx_authz_rules_count{type=\"file\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authorization Rate",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 14, "x": 10, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(emqx_authz_total{job=\"emqx-auth\",node='$node'}[$__interval]) or irate(emqx_authz_total{job=\"emqx-auth\",node='$node'}[$__interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(emqx_authz_allow{job=\"emqx-auth\",node='$node'}[$__interval]) or irate(emqx_authz_allow{job=\"emqx-auth\",node='$node'}[$__interval]))",
     "legendFormat": "Allow"
    },
    {
     "expr": "sum(rate(emqx_authz_deny{job=\"emqx-auth\",node='$node'}[$__interval]) or irate(emqx_authz_deny{job=\"emqx-auth\",node='$node'}[$__interval]))",
     "legendFormat": "Deny"
    },
    {
     "expr": "sum(rate(emqx_authz_nomatch{job=\"emqx-auth\",node='$node'}[$__interval]) or irate(emqx_authz_nomatch{job=\"emqx-auth\",node='$node'}[$__interval]))",
     "legendFormat": "No Match"
    }
   ]
  },
  {
   "title": "Match Total",
   "type": "stat",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(emqx_authz_total{type='$type'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allow Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(emqx_authz_allow{type='$type'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deny Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(emqx_authz_deny{type='$type'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No Match Counh",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(emqx_authz_nomatch{type='$type'})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}