{
 "title": "EMQX Stats Details",
 "description": "Default EMQX Grafana Monitoring Dashboard Template",
 "tags": [
  "EMQX",
  "MQTT"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "NodeName",
    "query": {
     "query": "label_values(emqx_connections_count,node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "repeat": "node",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "emqx_connections_count{instance=~\".*\",job=\"emqx-stats\",node='$node'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Topics",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(emqx_topics_count{instance=~\".*\",job=\"emqx-stats\"})",
     "legendFormat": "Active Topics"
    }
   ]
  },
  {
   "title": "Active Subscriptions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(emqx_suboptions_count{instance=~\".*\",job=\"emqx-stats\",node='$node'})"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(emqx_connections_count{instance=~\".*\",job=\"emqx-stats\",node='$node',node='$node'})",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "emqx_topics_count{instance=~\".*\",job=\"emqx-stats\"}",
     "legendFormat": "Topics"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "sum(emqx_suboptions_count{instance=~\".*\",job=\"emqx-stats\",node='$node'})",
     "legendFormat": "Subscriptions"
    }
   ]
  },
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(emqx_messages_received{instance=~\".*\",job=\"emqx-stats\",node='$node'}[20s]) or irate(emqx_messages_received{instance=~\".*\",job=\"emqx-stats\",node='$node'}[20s]))",
     "legendFormat": "Messages Received"
    },
    {
     "expr": "sum(rate(emqx_messages_sent{instance=~\".*\",job=\"emqx-stats\",node='$node'}[20s]) or irate(emqx_messages_sent{instance=~\".*\",job=\"emqx-stats\",node='$node'}[20s]))",
     "legendFormat": "Messages Sent"
    },
    {
     "expr": "sum(rate(emqx_messages_dropped{instance=~\".*\",job=\"emqx-stats\",node='$node'}[20s]) or irate(emqx_messages_dropped{instance=~\".*\",job=\"emqx-stats\",node='$node'}[20s]))",
     "legendFormat": "Messages Dropped"
    }
   ]
  },
  {
   "title": "Messages Sent Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(emqx_messages_sent{instance=~\".*\",job=\"emqx-stats\",node='$node'})"
    }
   ]
  },
  {
   "title": "Messages Received Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(emqx_messages_received{instance=~\".*\",job=\"emqx-stats\",node='$node'})"
    }
   ]
  },
  {
   "title": "Traffic Statistics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(emqx_bytes_received{instance=~\".*\",job=\"emqx-stats\",node='$node'}[20s]) or irate(emqx_bytes_received{instance=~\".*\",job=\"emqx-stats\",node='$node'}[20s]))",
     "legendFormat": "Bytes received"
    },
    {
     "expr": "sum(rate(emqx_bytes_sent{instance=~\".*\",job=\"emqx-stats\",node='$node'}[20s]) or irate(emqx_bytes_sent{instance=~\".*\",job=\"emqx-stats\",node='$node'}[20s]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "Retained Messages",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(emqx_retained_count{instance=~\".*\",job=\"emqx-stats\"})"
    }
   ]
  },
  {
   "title": "Messages Dropped Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(emqx_messages_dropped{instance=~\".*\",job=\"emqx-stats\",node='$node'})"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Erlang VM CPU Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(emqx_vm_cpu_use{instance=~\".*\",job=\"emqx-stats\",node='$node'})",
     "legendFormat": "VM CPU Used"
    }
   ]
  },
  {
   "title": "Erlang VM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(emqx_vm_used_memory{instance=~\".*\",job=\"emqx-stats\",node='$node'})",
     "legendFormat": "VM Memory Used"
    }
   ]
  },
  {
   "title": "Nodes status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(emqx_cluster_nodes_running{instance=~\".*\",job=\"emqx-stats\",node='$node'})",
     "legendFormat": "EMQX Nodes running"
    },
    {
     "expr": "max(emqx_cluster_nodes_stopped{instance=~\".*\",job=\"emqx-stats\",node='$node'})",
     "legendFormat": "EMQX Nodes stopped"
    }
   ]
  },
  { "title": "Packets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Packets Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(emqx_packets_connect{instance=~\".*\",job=\"emqx-stats\",node='$node'}[$__interval]) or irate(emqx_packets_connect{instance=~\".*\",job=\"emqx-stats\",node='$node'}[$__interval]))",
     "legendFormat": "Packets Connect"
    },
    {
     "expr": "sum(rate(emqx_packets_connack_sent{instance=~\".*\",job=\"emqx-stats\",node='$node'}[$__interval]) or irate(emqx_packets_connack_sent{instance=~\".*\",job=\"emqx-stats\",node='$node'}[$__interval]))",
     "legendFormat": "Packets Connack Sent"
    },
    {
     "expr": "sum(rate(emqx_packets_connack_error{instance=~\".*\",job=\"emqx-stats\",node='$node'}[$__interval]) or irate(emqx_packets_connack_error{instance=~\".*\",job=\"emqx-stats\",node='$node'}[$__interval]))",
     "legendFormat": "Packets Connack Error"
    }
   ]
  },
  {
   "title": "Packets Disconnect",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(emqx_packets_disconnect_sent{instance=~\".*\",job=\"emqx-stats\",node='$node'}[$__interval]) or irate(emqx_packets_disconnect_sent{instance=~\".*\",job=\"emqx-stats\",node='$node'}[$__interval]))",
     "legendFormat": "Packets Disconnect Sent"
    },
    {
     "expr": "sum(rate(emqx_packets_disconnect_received{instance=~\".*\",job=\"emqx-stats\",node='$node'}[$__interval]) or irate(emqx_packets_disconnect_received{instance=~\".*\",job=\"emqx-stats\",node='$node'}[$__interval]))",
     "legendFormat": "Packets Disconnect Received"
    }
   ]
  },
  {
   "title": "Packets Publish",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(rate(emqx_packets_publish_sent{instance=~\".*\",job=\"emqx-stats\",node='$node'}[$__interval]) or irate(emqx_packets_publish_sent{instance=~\".*\",job=\"emqx-stats\",node='$node'}[$__interval]))",
     "legendFormat": "Packets Publish Sent"
    },
    {
     "expr": "sum(rate(emqx_packets_publish_received{instance=~\".*\",job=\"emqx-stats\",node='$node'}[$__interval]) or irate(emqx_packets_publish_received{instance=~\".*\",job=\"emqx-stats\",node='$node'}[$__interval]))",
     "legendFormat": "Packets Publish Received"
    },
    {
     "expr": "sum(rate(emqx_packets_publish_dropped{instance=~\".*\",job=\"emqx-stats\",node='$node'}[$__interval]) or irate(emqx_packets_publish_dropped{instance=~\".*\",job=\"emqx-stats\",node='$node'}[$__interval]))",
     "legendFormat": "Packets Publish Dropped"
    },
    {
     "expr": "sum(rate(emqx_packets_publish_error{instance=~\".*\",job=\"emqx-stats\",node='$node'}[$__interval]) or irate(emqx_packets_publish_error{instance=~\".*\",job=\"emqx-stats\",node='$node'}[$__interval]))",
     "legendFormat": "Packets Publish Error"
    }
   ]
  },
  {
   "title": "Packets Subscribe/Unsubscribe",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum(rate(emqx_packets_subscribe_received{instance=~\".*\",job=\"emqx-stats\",node='$node'}[$__interval]) or irate(emqx_packets_subscribe_received{instance=~\".*\",job=\"emqx-stats\",node='$node'}[$__interval]))",
     "legendFormat": "Packets Subscribe Received"
    },
    {
     "expr": "sum(rate(emqx_packets_suback_sent{instance=~\".*\",job=\"emqx-stats\",node='$node'}[$__interval]) or irate(emqx_packets_suback_sent{instance=~\".*\",job=\"emqx-stats\",node='$node'}[$__interval]))",
     "legendFormat": "Packets Suback Sent"
    },
    {
     "expr": "sum(rate(emqx_packets_subscribe_error{instance=~\".*\",job=\"emqx-stats\",node='$node'}[$__interval]) or irate(emqx_packets_subscribe_error{instance=~\".*\",job=\"emqx-stats\",node='$node'}[$__interval]))",
     "legendFormat": "Packets Subscribe Error"
    },
    {
     "expr": "sum(rate(emqx_packets_unsubscribe_received{instance=~\".*\",job=\"emqx-stats\",node='$node'}[$__interval]) or irate(emqx_packets_unsubscribe_received{instance=~\".*\",job=\"emqx-stats\",node='$node'}[$__interval]))",
     "legendFormat": "Packets Unsubscribe Received"
    },
    {
     "expr": "sum(rate(emqx_packets_unsubscribe_error{instance=~\".*\",job=\"emqx-stats\",node='$node'}[$__interval]) or irate(emqx_packets_unsubscribe_error{instance=~\".*\",job=\"emqx-stats\",node='$node'}[$__interval]))",
     "legendFormat": "Packets Unsubscribe Error"
    }
   ]
  }
 ]
}